'use strict';

/**
 * updater.js — Auto-update via electron-updater
 *
 * Uses electron-builder's `publish:` config (electron-builder.yml) to locate
 * the `latest.yml` / `latest-mac.yml` feed on the update server.
 *
 * FLOW:
 *   1. On startup + every 4 h: silently checks for a new version.
 *   2. If found: sends `update-available` IPC → renderer shows a badge/toast.
 *   3. User clicks "Download": renderer sends `download-update` → we start download.
 *   4. Download progress is streamed via `update-download-progress` IPC.
 *   5. When done: sends `update-downloaded` IPC → renderer shows "Restart to update".
 *   6. User clicks "Restart": renderer sends `install-update` → quitAndInstall().
 *      NSIS runs the new installer silently, replaces app files, restarts Skales.
 *
 * DATA SAFETY:
 *   ~/.skales-data  is stored in the user's HOME folder.
 *   NSIS (per-user install) only touches:
 *     %LOCALAPPDATA%\Programs\Skales\     ← app files (replaced on update)
 *   It NEVER touches the home folder → ALL credentials, memory, and API keys
 *   in ~/.skales-data survive every update automatically.
 *
 * WHAT electron-updater NEEDS ON THE SERVER:
 *   https://skales.app/updates/latest.yml          ← auto-generated by electron-builder
 *   https://skales.app/updates/Skales Setup X.Y.Z.exe  ← the installer
 *   (macOS: latest-mac.yml + Skales-X.Y.Z.dmg)
 */

const { autoUpdater } = require('electron-updater');
const { app, ipcMain } = require('electron');

function setupUpdater(getMainWindow) {
  // ── Dev guard ─────────────────────────────────────────────────────────────
  if (!app.isPackaged) {
    console.log('[Updater] Skipping auto-update in development mode.');
    return;
  }

  // ── Logging ───────────────────────────────────────────────────────────────
  autoUpdater.logger = console;

  // ── Options ───────────────────────────────────────────────────────────────
  autoUpdater.autoDownload = false;         // User must confirm download
  autoUpdater.autoInstallOnAppQuit = true;  // Install on next quit if downloaded

  // ── Helper: forward event to renderer ────────────────────────────────────
  function send(channel, ...args) {
    const win = getMainWindow && getMainWindow();
    if (win && !win.isDestroyed()) {
      win.webContents.send(channel, ...args);
    }
  }

  // ── Events ────────────────────────────────────────────────────────────────
  autoUpdater.on('checking-for-update', () => {
    console.log('[Updater] Checking for update…');
  });

  autoUpdater.on('update-available', (info) => {
    console.log(`[Updater] Update available: v${info.version}`);
    send('update-available', {
      version:      info.version,
      releaseDate:  info.releaseDate,
      releaseNotes: info.releaseNotes ?? null,
    });
  });

  autoUpdater.on('update-not-available', (info) => {
    console.log(`[Updater] Already on the latest version (v${info.version}).`);
    send('update-not-available', { version: info.version });
  });

  autoUpdater.on('download-progress', (progress) => {
    const pct = Math.round(progress.percent);
    const kbs = Math.round(progress.bytesPerSecond / 1024);
    console.log(`[Updater] Downloading: ${pct}% (${kbs} KB/s)`);
    send('update-download-progress', {
      percent:        progress.percent,
      bytesPerSecond: progress.bytesPerSecond,
      transferred:    progress.transferred,
      total:          progress.total,
    });
  });

  autoUpdater.on('update-downloaded', (info) => {
    console.log(`[Updater] v${info.version} downloaded — ready to install.`);
    send('update-downloaded', {
      version:     info.version,
      releaseDate: info.releaseDate,
    });
  });

  autoUpdater.on('error', (err) => {
    // Filter out noisy "no update feed" errors in environments without internet
    const msg = err.message || String(err);
    console.error('[Updater] Error:', msg);
    send('update-error', msg);
  });

  // ── IPC: manual "Check for Updates" from renderer ─────────────────────────
  ipcMain.on('check-update', () => {
    console.log('[Updater] Manual check triggered.');
    autoUpdater.checkForUpdates().catch((err) => {
      console.error('[Updater] Manual check failed:', err.message);
      send('update-error', err.message);
    });
  });

  // ── IPC: renderer confirmed "Download Update" ─────────────────────────────
  ipcMain.on('download-update', () => {
    console.log('[Updater] Renderer confirmed download — starting…');
    autoUpdater.downloadUpdate().catch((err) => {
      console.error('[Updater] Download failed:', err.message);
      send('update-error', err.message);
    });
  });

  // ── IPC: renderer confirmed "Restart & Install" ───────────────────────────
  ipcMain.on('install-update', () => {
    console.log('[Updater] Installing update and restarting…');
    // isSilent=false  → shows the standard NSIS progress dialog
    // isForceRunAfter → ensures Skales relaunches after install
    autoUpdater.quitAndInstall(false, true);
  });

  // ── Initial check + periodic poll ─────────────────────────────────────────
  autoUpdater.checkForUpdates().catch((err) => {
    console.error('[Updater] Initial check failed:', err.message);
  });

  setInterval(() => {
    autoUpdater.checkForUpdates().catch((err) => {
      console.error('[Updater] Periodic check failed:', err.message);
    });
  }, 4 * 60 * 60 * 1000); // every 4 hours
}

module.exports = { setupUpdater };
