/**
 * Skales — Shared Skill AI Utilities
 *
 * Used by both /api/custom-skills/generate and /api/custom-skills/fix so that
 * buildSystemPrompt, callLLM, extractCode, and validateSkillCode are defined
 * in exactly one place.
 */

import fs   from 'fs';
import path from 'path';

// ─── System prompt builder ────────────────────────────────────────────────────

export function buildSystemPrompt(meta: {
    name:             string;
    category:         string;
    icon:             string;
    hasUI:            boolean;
    menuName?:        string;
    requiresApiKeys?: boolean;
}): string {
    const slug = meta.name.toLowerCase().replace(/[^a-z0-9]+/g, '-');

    const menuBlock = meta.hasUI
        ? `hasUI: true,\n  menuName: ${JSON.stringify(meta.menuName ?? meta.name)},\n  menuRoute: "/custom/${slug}",`
        : `hasUI: false,`;

    const secretsBlock = meta.requiresApiKeys
        ? `\n  // List every external API key or secret this skill needs.\n  // Skales will prompt the user to enter each before the skill can run.\n  requiredSecrets: [\n    { key: "<SECRET_KEY_NAME>", label: "<Human Readable Label>", placeholder: "sk-..." },\n  ],`
        : '';

    const uiPlaybook = meta.hasUI ? `

UI SKILL RULES — READ CAREFULLY:
The Skales framework automatically renders your skill's UI at /custom/${slug}.
Your execute() function ONLY needs to return structured data — the framework handles ALL rendering.
DO NOT write React/JSX code. DO NOT require('react'). DO NOT use browser APIs.
The framework renders data automatically based on the "type" field you return.

AVAILABLE RETURN TYPES from execute():

1. GALLERY (for images/media):
   return { success: true, result: {
     type: 'gallery',
     images: [
       { path: '/abs/path/to/img.png', name: 'filename.png', url: '/api/custom-skills/image?path=<encoded>', size: 1234 }
     ]
   }};
   For the url field, use: '/api/custom-skills/image?path=' + encodeURIComponent(absolutePath)

2. TABLE (for tabular data):
   return { success: true, result: {
     type: 'table',
     rows: [{ column1: 'val', column2: 'val' }, ...]
   }};

3. TEXT (for plain text output):
   return { success: true, result: { type: 'text', text: 'Your text here...' } };

4. HTML (for rich formatted output):
   return { success: true, result: { type: 'html', html: '<h2>Hello</h2><p>Content</p>' } };

CONTEXT OBJECT available in execute(input, context):
- context.dataDir       — Skales internal data dir (e.g. ~/.skales-data)
- context.workspacePath — User's workspace folder (where their files/images live). USE THIS for scanning user files.
- context.settings      — Full Skales settings object

IMPORTANT: Always use context.workspacePath (not context.dataDir + '/workspace') when scanning for user files.
The user's images, documents and data are in context.workspacePath.` : '';

    return `You are a Skales Skill AI — an expert Node.js developer who generates Skales v5 custom skill modules.

STRICT OUTPUT RULES:
1. Output ONLY valid JavaScript code — no markdown fences, no explanations, no commentary.
2. The file must export a CommonJS module (module.exports = { ... }).
3. The skill metadata must exactly match the values provided below.
4. The execute() function must be async and return { success: boolean, result?: any, error?: string }.
5. Use ONLY Node.js built-in modules: fs, path, https, http, crypto, os, util, child_process.
   NEVER use: require('react'), require('react-dom'), or any browser/UI library.
   NEVER write JSX or HTML template strings (unless result type is 'html').
6. The code must be production-quality: handle errors gracefully, validate inputs, and include clear comments.
7. If requiredSecrets is present, READ secrets like this inside execute():
   const apiKey = context.settings?.secrets?.['<SECRET_KEY_NAME>'] ?? '';
   if (!apiKey) return { success: false, error: 'Missing API key. Configure it in Skill Settings.' };${uiPlaybook}

REQUIRED MODULE STRUCTURE (fill in the execute body based on the user prompt):
\`\`\`
// ─── Skales Custom Skill ─────────────────────────────────────────
// Generated by Skill AI — Skales v5
'use strict';

const fs   = require('fs');
const path = require('path');

module.exports = {
  name:        ${JSON.stringify(meta.name)},
  id:          "${slug}",
  description: "<one-line description of what this skill does>",
  category:    "${meta.category}",
  icon:        ${JSON.stringify(meta.icon)},
  version:     "1.0.0",
  author:      "Skill AI",
  ${menuBlock}${secretsBlock}

  /**
   * @param {object} input   - Input data (depends on how the skill is invoked)
   * @param {object} context - Skales context: { dataDir: string, workspacePath: string, settings: object }
   * @returns {Promise<{success: boolean, result?: any, error?: string}>}
   */
  async execute(input, context) {
    try {
      // context.workspacePath = user's workspace folder (where their files/images live)
      // context.dataDir       = Skales internal data dir (~/.skales-data)
      const workspaceDir = context.workspacePath || path.join(context.dataDir, 'workspace');

      // === YOUR SKILL LOGIC HERE (Node.js only — no React/browser code) ===

      return { success: true, result: { type: 'text', text: 'Done.' } };
    } catch (err) {
      return { success: false, error: err.message ?? String(err) };
    }
  },
};
\`\`\`

Now generate the complete skill based on the user's requirements below.`;
}

// ─── LLM caller — provider-agnostic ──────────────────────────────────────────

export async function callLLM(
    settings: any,
    provider: string,
    model:    string,
    systemPrompt: string,
    userPrompt:   string,
): Promise<string> {
    const apiKey  = settings?.providers?.[provider]?.apiKey ?? '';
    const baseUrl = settings?.providers?.[provider]?.baseUrl ?? '';

    const ENDPOINTS: Record<string, string> = {
        openrouter: 'https://openrouter.ai/api/v1/chat/completions',
        openai:     'https://api.openai.com/v1/chat/completions',
        anthropic:  'https://api.anthropic.com/v1/messages',
        groq:       'https://api.groq.com/openai/v1/chat/completions',
        mistral:    'https://api.mistral.ai/v1/chat/completions',
        deepseek:   'https://api.deepseek.com/v1/chat/completions',
        xai:        'https://api.x.ai/v1/chat/completions',
        together:   'https://api.together.xyz/v1/chat/completions',
        qiniu:      'https://api.qnaigc.com/v1/chat/completions',
        ollama:     `${baseUrl || 'http://localhost:11434/v1'}/chat/completions`,
        google:     'https://generativelanguage.googleapis.com/v1beta/openai/chat/completions',
    };

    const endpoint = ENDPOINTS[provider];
    if (!endpoint) throw new Error(`Unsupported provider: ${provider}`);

    if (provider === 'anthropic') {
        const res = await fetch(endpoint, {
            method: 'POST',
            headers: {
                'x-api-key':         apiKey,
                'anthropic-version': '2023-06-01',
                'content-type':      'application/json',
            },
            body: JSON.stringify({
                model,
                max_tokens: 16384,
                system: systemPrompt,
                messages: [{ role: 'user', content: userPrompt }],
            }),
        });
        if (!res.ok) throw new Error(`Anthropic API error ${res.status}: ${await res.text()}`);
        const data = await res.json();
        return (data?.content?.[0]?.text ?? '').trim();
    }

    const headers: Record<string, string> = {
        'content-type':  'application/json',
        'authorization': `Bearer ${apiKey}`,
    };
    if (provider === 'openrouter') {
        headers['http-referer'] = 'https://skales.app';
        headers['x-title']     = 'Skales Skill AI';
    }

    const res = await fetch(endpoint, {
        method: 'POST',
        headers,
        body: JSON.stringify({
            model,
            max_tokens: 16384,
            temperature: 0.2,
            messages: [
                { role: 'system', content: systemPrompt },
                { role: 'user',   content: userPrompt },
            ],
        }),
    });
    if (!res.ok) throw new Error(`LLM API error ${res.status}: ${await res.text()}`);
    const data = await res.json();
    return (data?.choices?.[0]?.message?.content ?? '').trim();
}

// ─── Code fence stripper ──────────────────────────────────────────────────────

/** Strip markdown code fences from LLM output (in case the model adds them). */
export function extractCode(raw: string): string {
    return raw
        .replace(/^```(?:javascript|js|typescript|ts)?\n?/i, '')
        .replace(/\n?```\s*$/, '')
        .trim();
}

// ─── Skill code validator ─────────────────────────────────────────────────────

/**
 * Validates generated skill code entirely IN-MEMORY using Node.js vm.Script.
 *
 * WHY no temp files: on Windows, Defender quarantines newly created .js files
 * in %TEMP% before require() can read them. vm.Script avoids all file I/O.
 *
 * WHY eval('require'): In Next.js, the module-level `require` is webpack's
 * __webpack_require__ which cannot resolve core Node.js modules (fs, path,
 * net…) when called from inside vm.runInThisContext. eval('require') bypasses
 * webpack's static analysis and returns the genuine native Node.js require()
 * that ALWAYS resolves built-ins and arbitrary runtime paths.
 *
 * Three checks:
 *   1. Syntax check — vm.Script compilation (fast, no execution)
 *   2. Module structure — evaluate via CommonJS wrapper, check execute() exists
 *   3. Runtime test   — call execute() with dummy context; allow soft errors
 *                       (network, missing files, missing npm packages) that are
 *                       expected in a validation-only environment.
 */
import vm from 'vm';
import { SKILLS_DIR } from '@/lib/paths';

/** NODE.JS CORE MODULE LIST — these are always soft-errors if they somehow fail */
const NODE_CORE_MODULES = new Set([
    'fs', 'path', 'http', 'https', 'net', 'os', 'child_process', 'crypto',
    'url', 'util', 'stream', 'events', 'buffer', 'querystring', 'zlib',
    'readline', 'assert', 'timers', 'dns', 'tls', 'worker_threads',
    'cluster', 'module', 'v8', 'vm', 'perf_hooks', 'process',
]);

/**
 * Get the REAL Node.js require, bypassing webpack's __webpack_require__.
 *
 * In Next.js, `require` at module level is webpack's transformed require which
 * CANNOT dynamically resolve core modules like 'fs' from inside vm.runInThisContext.
 * eval('require') is the standard trick to obtain the native Node.js require
 * because webpack cannot statically analyze eval().
 *
 * THIS FIXES: "require is not a function" and "Cannot find module 'fs'" errors.
 */
// eslint-disable-next-line no-eval
const nativeRequire: NodeRequire = eval('require');

/**
 * Sandbox require function for skill validation.
 * Wraps nativeRequire with node: prefix normalization and core-module awareness.
 */
function sandboxRequire(moduleName: string): any {
    // Normalize 'node:fs' → 'fs'
    const name = moduleName.startsWith('node:') ? moduleName.slice(5) : moduleName;
    return nativeRequire(name);
}

export async function validateSkillCode(
    code: string,
): Promise<{ valid: boolean; error?: string }> {

    // ── Step 1: Syntax check (no execution) ──────────────────────────────────
    try {
        new vm.Script(code, { filename: 'skill-validate.js' });
    } catch (syntaxErr: any) {
        return { valid: false, error: `Syntax error: ${syntaxErr.message ?? String(syntaxErr)}` };
    }

    // ── Step 2: Module evaluation in a CommonJS wrapper ──────────────────────
    const fakeModule = { exports: {} as any };
    try {
        const wrapped = `(function(module,exports,require,__dirname,__filename){\n${code}\n})`;
        const fn = vm.runInThisContext(wrapped, { filename: 'skill-validate.js' });
        // Use sandboxRequire (native Node require via eval) so that
        // require('fs'), require('path') etc. ALWAYS resolve correctly.
        fn(fakeModule, fakeModule.exports, sandboxRequire, SKILLS_DIR, path.join(SKILLS_DIR, '_validate.js'));
    } catch (loadErr: any) {
        const msg = loadErr.message ?? String(loadErr);

        if (/Cannot find module/i.test(msg)) {
            // Determine which module is missing
            const missingRaw = msg.match(/Cannot find module '([^']+)'/)?.[1] ?? '';
            const missing    = missingRaw.startsWith('node:') ? missingRaw.slice(5) : missingRaw;

            if (NODE_CORE_MODULES.has(missing)) {
                // Core module should NEVER fail with native require.
                // If it does, accept the skill — it will work at runtime.
                return { valid: true };
            }
            // Third-party npm package not installed in validation env — soft error.
            // Accept if execute() was already exported before the missing dep failed.
            if (typeof fakeModule.exports?.execute === 'function') {
                return { valid: true };
            }
            return { valid: false, error: `npm package "${missing}" not available in validation sandbox: ${msg}` };
        }
        return { valid: false, error: `Module load error: ${msg}` };
    }

    if (typeof fakeModule.exports?.execute !== 'function') {
        return { valid: false, error: 'Module does not export an execute() function' };
    }

    // ── Step 3: Light runtime test ────────────────────────────────────────────
    const testContext = {
        dataDir:       SKILLS_DIR,
        workspacePath: SKILLS_DIR,
        settings:      {},
    };

    try {
        const result = await fakeModule.exports.execute({}, testContext);
        if (result === undefined || result === null) {
            return { valid: false, error: 'execute() returned null/undefined — must return { success: boolean }' };
        }
    } catch (execErr: any) {
        const msg = execErr.message ?? String(execErr);
        // Soft errors expected in sandbox: network, missing files, missing npm packages
        const isSoft = /ENOTFOUND|ECONNREFUSED|ETIMEDOUT|ENOENT|EPERM|fetch|network|socket|Cannot find module|permission|not found/i.test(msg);
        if (!isSoft) {
            return { valid: false, error: `execute() threw: ${msg}` };
        }
    }

    return { valid: true };
}
